apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::716366439262:role/MyEksCluster-workers-NodeInstanceRole-UK09BSTF280Z
      groups:
        - system:bootstrappers
        - system:nodes
