apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01USXlNVEF6TkRJMU9Wb1hEVE13TVRJeE9UQXpOREkxT1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTjhOCjFNenN6MFNVOGZmQnVNeisrcHhVbjFQclVJL1ZqbVA5Wlc1eUhLM0cvcGlqNWdheUU0UURQZzlEOHBHazZaclkKdjBTLytLMlA4Tm5RNkhFVkpIVFR5UDd0dXN6elU1a1lNTmk2YlVlL053RmtCMG55ZVFxTHpYK0ViZGZHdlM5WgptVDNXS1JwVFZ3QXgySzloSDlvcWsxdllDSTU1VXBpZmhJUkQ2N2hPWVJ0S2xiZGdkaDF3bXc0NUlIcnNVU1Q5ClVPM0ZMU3ZFVzlqQ2x2WjZJTzF6VXdYakFtVHFPd0pYZXpyYmFDRG1iZFJ4N0trdW1Id1d4dEpEdnhQdklla3UKVGloSEt2K2ZrbnBZV2tsNVloM3l5NFJJaUJjd2ZNS2NtMmQ4MXJoZFZNVjRFeDlpYnRKYjFiS3pnd1VCdHVORAp3OW8vMjRWVktGbktreGxJb3ZFQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCYk8zODdhaDhremJjNGFrZ0I2UHVPNS83WW8KdnI0akptdUFSaUJhZ0dNSUxUR3ZoUExKZ3RYMUpBbG9sWG9VZFBxYkJCWk9yR29JL1ZEanJLZ05vK0RwK2k3RwpFK0gybmhzN3phY3hNR3JuWHQ4Tzc2em93WDJMTlNsSzZPcFN0VzdwcUhuZTVwQ20veUwrMTFETWxoTUhwaFd0CjE0alBHL2NYdXRRbjJOcGlqT2xvT2ptNUFKSXFqZld6UEdyOHl1VHgxa1J5ZUlIcWRtQXRSMUZrRC9jWVkydEcKRURGZ0NOUG5EY1NsVm5tY1JQTjl2UkM1YmZrZ0p1bzU0L0g4MUFocVFOa1lKK2VHTDVjekV2QWFpNHp3ek82bwpLVlRubThLYUtpNDNhMnIrM1NabXpYdEVkbVBybzNQWStxdkYwOUFmWWZyQkdoYnNQaFpkRUxIZVBsRT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://0F07973065FCF9D742BF38A18E9429EB.sk1.ap-south-1.eks.amazonaws.com
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - MyEksCluster
      command: heptio-authenticator-aws
