apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-mumbai-mgd-cluster
  region: ap-south-1
  version: "1.18"
vpc:
  id: vpc-0389dbee09ffe425b

  cidr: "192.168.0.0/16"
  subnets:
    public:
      ap-south-1a:
        id: subnet-07ef09b0862d182e2

      ap-south-1b:
        id: subnet-01ef14414483fde4b

    private:
      ap-south-1a:
        id: subnet-0e9f2c8678d7708f1

      ap-south-1b:
        id: subnet-0c117800b2fbaae24


managedNodeGroups:
  - name: EKS-managed-public-workers
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    volumeSize: 5
    instanceType: t2.micro
  - name: EKS-managed-private-workers
    instanceType: t2.micro
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    privateNetworking: true
