apiVersion: v1
kind: PersistentVolume
metadata:
  name: mynfspersistentvolume
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt
    server: 192.168.1.1

  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-netapp
