AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template deploys and configures a NetApp Cloud Manager
  instance, and a NetApp ONTAP Cloud instance. The ONTAP Cloud system will be
  fully configured to serve up NFS, CIFS or iSCSI storage targets to your EC2
  compute. **WARNING** You will be billed for the AWS
  resources used if you create a stack from this template.
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - VPCId
          - SubnetId
          - RemoteAccessCIDR
      - Label:
          default: Amazon EC2 Configuration
        Parameters:
          - KeyPair
      - Label:
          default: ONTAP Cloud General Configuration
        Parameters:
          - UniqueResourceId
          - CompanyName
          - CloudManagerUserEmail
          - CloudManagerPassword
      - Label:
          default: AWS Quick Start Configuration
        Parameters:
          - QSS3BucketName
          - QSS3KeyPrefix
    ParameterLabels:
      CloudManagerPassword:
        default: Cloud Manager Password
      CloudManagerUserEmail:
        default: Cloud Manager User Email
      CompanyName:
        default: Company Name
      KeyPair:
        default: Key Name
      QSS3BucketName:
        default: Quick Start S3 Bucket Name
      QSS3KeyPrefix:
        default: Quick Start S3 Key Prefix
      RemoteAccessCIDR:
        default: Remote Access CIDR
      SubnetId:
        default: Subnet Id
      UniqueResourceId:
        default: Unique Resource Identifier
      VPCId:
        default: VPC Id
Parameters:
  CloudManagerPassword:
    ConstraintDescription: Password Min length is 8 and max length is 20
    Description: >-
      Password will be used to login to Cloud Manager and ONTAP Cloud. Must be
      of length between 8-20.
    MaxLength: '20'
    MinLength: '8'
    NoEcho: 'true'
    Type: String
  CloudManagerUserEmail:
    Description: Email address will be used to login to Cloud Manager
    Type: String
  CompanyName:
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9_]*'
    ConstraintDescription: >-
      Must start with alphabetic character and contains only numbers, letters or
      underscore (_) with minimum 4 and up to 35 characters
    Description: >-
      Company name. Should start with alphabetic character and contains only
      numbers, letters or underscore (_) with minimum 4 and up to 35 characters
    MaxLength: '35'
    MinLength: '4'
    Type: String
  KeyPair:
    Description: Key Name for the CloudManager instance
    Type: 'AWS::EC2::KeyPair::KeyName'
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: >-
      Quick Start bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: aws-quickstart
    Description: >-
      S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot
      start or end with a hyphen (-). Accept default for a bucket already
      configured.
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-]+(/[0-9a-zA-Z-]+)*$'
    ConstraintDescription: >-
      Quick Start key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/). It cannot start or end with a
      forward slash (/), which is automatically appended.
    Default: quickstart-netapp-ontapcloud-sql
    Description: >-
      S3 key prefix for the Quick Start assets. This prefix can include numbers,
      lowercase letters, uppercase letters, hyphens (-), and forward slash (/).
      It cannot start or end with a forward slash (/), which is automatically
      appended. Accept default for standard configuration.
    Type: String
  RemoteAccessCIDR:
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: Must be a valid CIDR range of the form x.x.x.x/x.
    Description: >-
      CloudManager and SQL Server access will be allowed from this CIDR range
      (example for full access: 0.0.0.0/0)
    MaxLength: '18'
    MinLength: '9'
    Type: String
  SubnetId:
    Description: Public SubnetID for Cloud Manager and ONTAP Cloud
    Type: 'AWS::EC2::Subnet::Id'
  UniqueResourceId:
    ConstraintDescription: Must be of length betweeen 4 and 40 chars.
    Default: NetApp-ONTAP-Cloud
    Description: >-
      A unique name to be used to identify the AWS resources deployed as part of
      this template.
    MaxLength: '40'
    MinLength: '4'
    Type: String
  VPCId:
    Description: Target VPC for Cloud Manager and ONTAP Cloud
    Type: 'AWS::EC2::VPC::Id'
Mappings:
  AWSInfoRegionMap:
    ap-northeast-1:
      Partition: aws
      QuickStartS3URL: 'https://s3.amazonaws.com'
    ap-northeast-2:
      Partition: aws
      QuickStartS3URL: 'https://s3.amazonaws.com'
    ap-south-1:
      Partition: aws
      QuickStartS3URL: 'https://s3.amazonaws.com'
    ap-southeast-1:
      Partition: aws
      QuickStartS3URL: 'https://s3.amazonaws.com'
    ap-southeast-2:
      Partition: aws
      QuickStartS3URL: 'https://s3.amazonaws.com'
    eu-central-1:
      Partition: aws
      QuickStartS3URL: 'https://s3.amazonaws.com'
    eu-west-1:
      Partition: aws
      QuickStartS3URL: 'https://s3.amazonaws.com'
    sa-east-1:
      Partition: aws
      QuickStartS3URL: 'https://s3.amazonaws.com'
    us-east-1:
      Partition: aws
      QuickStartS3URL: 'https://s3.amazonaws.com'
    us-east-2:
      Partition: aws
      QuickStartS3URL: 'https://s3.amazonaws.com'
    us-west-1:
      Partition: aws
      QuickStartS3URL: 'https://s3.amazonaws.com'
    us-west-2:
      Partition: aws
      QuickStartS3URL: 'https://s3.amazonaws.com'
Resources:
  OTC:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Join 
        - /
        - - !FindInMap 
            - AWSInfoRegionMap
            - !Ref 'AWS::Region'
            - QuickStartS3URL
          - !Ref QSS3BucketName
          - !Ref QSS3KeyPrefix
          - templates/netapp-otc.template
      Parameters:
        CloudManagerPassword: !Ref CloudManagerPassword
        CloudManagerUserEmail: !Ref CloudManagerUserEmail
        CompanyName: !Ref CompanyName
        KeyPair: !Ref KeyPair
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
        SubnetId: !Ref SubnetId
        UniqueResourceId: !Ref UniqueResourceId
        VPCId: !Ref VPCId
Outputs:
  CloudManagerURL:
    Description: CloudManager URL
    Value: !GetAtt 
      - OTC
      - Outputs.CloudManagerURL
  CVOMountPoint:
    Description: Mount Point for CVO Volume
    Value: !GetAtt 
      - OTC
      - Outputs.CVOMountPoint